/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kcd' at '17. 1. 6 오전 12:30' with Gradle 3.2.1
 *
 * @author kcd, @date 17. 1. 6 오전 12:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
